name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN }}
        issue-message: "Hi @${{ github.actor }}! Thanks for submitting your first Issue"
        pr-message: "Hi @${{ github.actor }} ! Thanks for submitting your first PR, Kindly Check the Contributor's guide for new users"
